# Site
name: "Janastu Blog"
title: "Janastu - Blog"
description: "Collection of Janastu stories"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
# google_analytics: 'UA-46278016-1'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  janastu:
    name: janastu
    display_name: Janastu
    avatar: assets/images/logo.png
    email: admin@janastu.org
    web: janastu.org
    twitter: https://twitter.com/anthillhacks
    description: "Author profile"
  bhanu:
    name: Bhanu
    display_name: Salus Sage
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: salus.sage@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/salus-sage
    description: "Author profile"
  tbd:
    name: TB Dinesh
    display_name: janteel   
    avatar: 'assets/images/tbd-gravatar.gif'
    # gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: dinesh@servelots.com
    web: janastu.org
    twitter: https://twitter.com/tbdinesh
    description: "Author profile"
  mani:
    name: Manikantan
    display_name: Mani    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: mani@servelots.com
    web: janastu.org
    twitter: https://twitter.com/themanikantan
    description: "Author profile"
  sanketh:
    name: Sanketh
    display_name: Sanketh    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: sanketh@servelots.com
    web: janastu.org
    twitter: https://twitter.com
    description: "Author profile"
  shalini:
    name: Shalini
    display_name: The Boss    
    avatar: 'assets/images/favatar.png'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: shalini@servelots.com
    web: janastu.org
    twitter: https://twitter.com
    description: "Author profile"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
# adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
